residence/control/urls.py
from django.urls import path
from . import views

app_name = 'control'

urlpatterns = [
    path('', views.index,name='index'),
    path('propietario/', views.registrar_propietario, name='registrar_propietario'),
    path('vehiculo/', views.registrar_vehiculo, name='registrar_vehiculo'),
    path('registro/', views.registrar_registro, name='registrar_registro'),
]

residence/residence/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('control/', include('control.urls', namespace='control'))
]

residence/control/models.py
from django.db import models

# Create your models here.
class Propietario(models.Model):
    nombre=models.CharField(max_length=30)
    numero_apartamento=models.IntegerField()
    telefono=models.CharField(max_length=15)
    email=models.EmailField()

    def __str__(self):
        return self.nombre
    
class Vehiculo(models.Model):
    propietario=models.ForeignKey(Propietario, on_delete=models.CASCADE)
    matricula=models.CharField(max_length=8, unique=True)
    marca=models.CharField(max_length=15)
    modelo=models.CharField(max_length=20)
    color=models.CharField(max_length=20)

    def __str__(self):
        return f'{self.marca} - {self.matricula}'

class Registro(models.Model):
    vehiculo=models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    fecha_hora_entrada=models.DateTimeField()
    fecha_hora_salida=models.DateTimeField(null=True, blank=True)

residence/control/forms.py
from django import forms
from .models import Propietario, Vehiculo, Registro

class PropietarioForm(forms.ModelForm):
    class Meta:
        model = Propietario
        fields = ['nombre', 'numero_apartamento', 'telefono', 'email']

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ['propietario', 'matricula', 'marca', 'modelo', 'color']

class RegistroForm(forms.ModelForm):
    class Meta:
        model = Registro
        fields = ['vehiculo', 'fecha_hora_entrada', 'fecha_hora_salida']
        

residence/control/views.py
from django.shortcuts import render, redirect
from .forms import PropietarioForm, VehiculoForm, RegistroForm
from .models import Propietario, Vehiculo, Registro

# Create your views here.

def index(request):
    return render(request, 'control/index.html')

def registrar_propietario(request):
    if request.method == 'POST':
        form = PropietarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('control:index')  
    else:
        form = PropietarioForm()
    return render(request, 'control/registrar_propietario.html', {'form': form})

def registrar_vehiculo(request):
    if request.method == 'POST':
        form = VehiculoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('control:index')  
    else:
        form = VehiculoForm()
    return render(request, 'control/registrar_vehiculo.html', {'form': form})

def registrar_registro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('control:index') 
    else:
        form = RegistroForm()
    return render(request, 'control/registrar_registro.html', {'form': form})

residence/control/templates/control/index.html
{% load static %}
<html>
<head>
    <title>Condominio</title>
    <link rel="stylesheet" type="text/css" href="{% static 'control/styles.css' %}">
</head>
<body>
    <h1>Seleccionar</h1>
    <ul>
        <li>
            <a href="{% url 'control:registrar_propietario' %}">Registro de Propietario</a>
        </li>
        <li>
            <a href="{% url 'control:registrar_vehiculo' %}">Registro de Vehículo</a>
        </li>
        <li>
            <a href="{% url 'control:registrar_registro' %}">Registro de Entrada y Salida</a>
        </li>
    </ul>
</body>
</html>

residence/control/templates/control/registrar_propietario.html
{% load static %}
<html>
<head>
    <title>Registrar Propietario</title>
    <link rel="stylesheet" type="text/css" href="{% static 'control/styles.css' %}">
</head>
<body>
    <h1>Datos del Propietario</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    <a href="{% url 'control:index' %}">Volver al Inicio</a> 
</body>
</html>


residence/control/templates/control/registrar_registro.html
{% load static %}
<html>
<head>
    <title>Registro</title>
    <link rel="stylesheet" type="text/css" href="{% static 'control/styles.css' %}">
</head>
<body>
    <h1>Datos de Registro</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    <a href="{% url 'control:index' %}">Volver al Inicio</a> 
</body>
</html>

residence/control/templates/control/registrar_vehiculo.html
{% load static %}
<html>
<head>
    <title>Registrar Vehículo</title>
    <link rel="stylesheet" type="text/css" href="{% static 'control/styles.css' %}">
</head>
<body>
    <h1>Datos de Vehículo</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    <a href="{% url 'control:index' %}">Volver al Inicio</a>
</body>
</html>